name: 'Nx distributed task'
branding:
  icon: chevron-right
  color: white
description: "Executes Nx task"
inputs:
  target:
    description: "Target to run"
    required: true
  projects:
    description: "Comma-delimited list of projects to run against target"
    required: true
  distribution:
    description: "Current distribution run, required when running in a matrix"
    required: false
  bucket:
    description: "Current distribution run, required when running in a matrix"
    required: false
    deprecationMessage: "deprecated, use distribution input instead"
  maxParallel:
    description: "Maximum NX cli parallel runs"
    required: false
    default: '3'
  uploadOutputs:
    description: "Should upload target's outputs from all distributed jobs"
    required: false
    default: 'true'
  args:
    description: 'space-delimited args to add to nx command execution'
    required: false
  nxCloud:
    description: 'Enable support of Nx Cloud'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
