name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: e-square-io/.github/.github/actions/npm-ci@main

      - name: Calculate Affected Projects
        uses: e-square-io/nx-affected-matrix@v2
        id: affected
        with:
          targets: 'test,build'

  execute:
    name: Run ${{ matrix.target }} ${{ matrix.distribution }}
    if: ${{ needs.setup.outputs.hasChanges == 'true' }}
    runs-on: ubuntu-latest
    needs: [ setup ]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2

      - uses: e-square-io/.github/.github/actions/npm-ci@main

      - name: Run semantic-release locally
        if: ${{ matrix.target == 'build' }}
        uses: e-square-io/.github/.github/actions/semantic-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

      - name: Execute target
        uses: e-square-io/nx-distributed-task@v2
        id: execute
        with:
          target: ${{ matrix.target }}
          distribution: ${{ matrix.distribution }}
          projects: ${{ matrix.projects }}
          nxCloud: true

      - uses: e-square-io/.github/.github/actions/nx-codecov@main
        if: ${{ matrix.target == 'test' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          path: coverage/packages

  e2e-distribute:
    name: E2E nx-affected-matrix
    if: ${{ needs.setup.outputs.hasChanges == 'true'  && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')  }}
    needs: [setup, execute]
    runs-on: ubuntu-latest
    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges || needs.setup.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix || needs.setup.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: e-square-io/.github/.github/actions/npm-ci@main

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Run local matrix action
        if: ${{ contains(needs.setup.outputs.matrix, 'nx-affected-matrix') }}
        uses: ./dist/packages/nx-affected-matrix
        id: affected
        with:
          targets: 'build'
          maxDistribution: 1
          debug: true

  e2e-execute:
    name: 'E2E nx-distributed-task [${{ matrix.target }} (${{ matrix.distribution }})]'
    if: ${{ needs.e2e-distribute.outputs.hasChanges == 'true' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && contains(needs.setup.outputs.matrix, 'nx-distributed-task') }}
    needs: [setup,e2e-distribute]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.target == 'test' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.e2e-distribute.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: e-square-io/.github/.github/actions/npm-ci@main

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Run local distributed task action
        uses: ./dist/packages/nx-distributed-task
        id: run
        with:
          target: ${{ matrix.target }}
          distribution: ${{ matrix.distribution }}
          projects: ${{ matrix.projects }}
          debug: true

  release:
    name: Release version
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.hasChanges == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [setup, execute]
    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Obtain GitHub App Installation Access Token
        uses: e-square-io/.github/.github/actions/get-app-token@main
        id: githubAppAuth
        with:
          token: ${{ secrets.GH_AUTH_SECRET }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Semantic release
        id: release
        uses: e-square-io/.github/.github/actions/semantic-release@main
        with:
          github-token: ${{ steps.githubAppAuth.outputs.github-token }}
          npm-token: ${{ secrets.NPM_TOKEN }}

  publish:
    name: Publish actions
    if: ${{ needs.release.outputs.released }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ['nx-affected-matrix', 'nx-distributed-task']
    needs: [setup, execute, release]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Publish action ${{ matrix.package }}
        if: ${{ contains(needs.setup.outputs.matrix, matrix.package) }}
        uses: e-square-io/.github/.github/actions/push-to-repo@main
        with:
          path: 'dist/packages/${{ matrix.package }}'
          github-token: ${{ needs.release.outputs.gh-app-token }}
          version: ${{ needs.release.outputs.version }}
          repository: ${{ matrix.package }}
