name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ubuntu-latest
    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci --cache .npm

      - name: Calculate affected
        uses: e-square-io/nx-affected-matrix@v1
        id: affected
        with:
          targets: 'test,build'

  execute:
    name: ${{ matrix.target }} (${{ matrix.distribution }})
    if: ${{ needs.setup.outputs.hasChanges == 'true' }}
    needs: [setup]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.target == 'test' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci --cache .npm

      - name: Execute target
        uses: e-square-io/nx-distributed-task@v1
        id: run
        with:
          nxCloud: true
          target: ${{ matrix.target }}
          bucket: ${{ matrix.distribution }}
          projects: ${{ matrix.projects }}

  coverage:
    name: Publish coverage
    runs-on: ubuntu-latest
    needs: [execute]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: test

      - uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/packages/*
