name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ubuntu-latest
    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Calculate affected
        uses: e-square-io/nx-affected-matrix@v2
        id: affected
        with:
          targets: 'test,build'
          maxDistribution: 1 # the project is still small and its faster not to distribute

  execute:
    name: ${{ matrix.target }} (${{ matrix.distribution }})
    if: ${{ needs.setup.outputs.hasChanges == 'true' }}
    needs: [setup]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.target == 'test' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Execute target
        uses: e-square-io/nx-distributed-task@v2
        id: run
        with:
          nxCloud: true
          target: ${{ matrix.target }}
          distribution: ${{ matrix.distribution }}
          projects: ${{ matrix.projects }}

  e2e-distribute:
    name: E2E nx-affected-matrix
    if: ${{ needs.setup.outputs.hasChanges == 'true' }}
    needs: [setup, execute]
    runs-on: ubuntu-latest
    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges || needs.setup.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix || needs.setup.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Run local matrix action
        if: ${{ contains(needs.setup.outputs.matrix, 'nx-affected-matrix') }}
        uses: ./dist/packages/nx-affected-matrix
        id: affected
        with:
          targets: 'build'
          maxDistribution: 1
          debug: true

  e2e-execute:
    name: 'E2E nx-distributed-task [${{ matrix.target }} (${{ matrix.distribution }})]'
    if: ${{ needs.e2e-distribute.outputs.hasChanges == 'true' && contains(needs.setup.outputs.matrix, 'nx-distributed-task') }}
    needs: [setup,e2e-distribute]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.target == 'test' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.e2e-distribute.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Run local distributed task action
        uses: ./dist/packages/nx-distributed-task
        id: run
        with:
          target: ${{ matrix.target }}
          distribution: ${{ matrix.distribution }}
          projects: ${{ matrix.projects }}
          debug: true

  coverage:
    name: Publish coverage
    runs-on: ubuntu-latest
    needs: [execute]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: test

      - uses: codecov/codecov-action@v2
        with:
          file: coverage/packages/**/lcov.info
